ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS original_price DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS item_discount DECIMAL(10,2) NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS item_discount_type VARCHAR(10) NULL,
  ADD COLUMN IF NOT EXISTS sale_discount DECIMAL(10,2) NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sale_discount_type VARCHAR(10) NULL;